name: Terraform

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"

    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      continue-on-error: false

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate
      continue-on-error: false

    - name: Report Status
      run: |
        echo "✅ All Terraform checks passed successfully"
        echo "::notice::Terraform validation completed successfully"
      if: success()

    - name: Report Failure
      run: |
        echo "❌ Terraform checks failed"
        echo "::error::Terraform validation failed"
      if: failure()
	  